name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    env:
      version_to_increment: "1.2.3"
      expected_version: "1.2.4"
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: increment
        name: increment ${{ env.version_to_increment }}
        with:
          version: ${{ env.version_to_increment }}
      - name: show incremented version
        run: echo '${{ steps.increment.outputs.version }}'
      - name: Fail if default increment is not expected value ${{ env.expected_version }}
        if: ${{ steps.increment.outputs.version != env.expected_version }}
        run: |
          echo "Invalid version. Expected ${{ env.expected_version }}"
          exit 1



